__default__:
        partition: 'standard'
        group: 'bhurwitz'
        M: 'schackartk@email.arizona.edu'
        time: '00:05:00'
        nodes: '1'
        ntasks: '5'
        mem-per-cpu: '5gb'
        o: 'out/{rule}/{wildcards}.out'
        e: 'err/{rule}/{wildcards}.err'
