in_dir: "../../data/selected_frags_small"
out_dir: "../../data/classified_chopped_small"

deepvirfinder: "python ../../tool_envs/deepvirfinder/DeepVirFinder/dvf.py"
deepvirfinder_cores: 5

phamers: "python ../../tool_envs/phamers/PhaMers/scripts/phamer.py"

phigaro: "phigaro"
phigaro_threads: 4

seeker: "predict-metagenome"

kingdoms: ["archaea", "bacteria", "fungi", "viral"]

lengths: [500, 1000, 3000, 5000 ]
