in_dir: "../../data/selected_frags_small"
out_dir: "../../data/classified_chopped_small"

reformat: "python3 ../post_proc/reformat.py"
combine: "python3 ../post_proc/combine.py"

tools: ['dvf', 'seeker', 'virsorter', 'breadsticks']

breadsticks: "python ../../tool_envs/unlimited_breadsticks/Cenote_Unlimited_Breadsticks/unlimited_breadsticks.py"
breadsticks_env: "../../tool_envs/unlimited_breadsticks/env"
breadsticks_mem: 5
breadsticks_cpu: 8

deepvirfinder: "python ../../tool_envs/deepvirfinder/DeepVirFinder/dvf.py"
dvf_env: "../../tool_envs/deepvirfinder/env"
deepvirfinder_cores: 1

phamers: "python ../../tool_envs/phamers/PhaMers/scripts/phamer.py"

phigaro: "phigaro"
phigaro_threads: 4

seeker: "predict-metagenome"

virsorter: "virsorter run"
virsorter_env: "../../tool_envs/virsorter2/env"

kingdoms: ["archaea", "bacteria", "fungi", "viral"]

lengths: [500, 1000, 3000, 5000 ]
