in_dir: "../../data/selected_frags_small"
out_dir: "../../data/classified_chopped_small"

reformat: "python3 ../post_proc/reformat.py"
combine: "python3 ../post_proc/combine.py"
benchmark: "python3 ../post_proc/benchmark.py"

tools: ['dvf', 'seeker', 'vibrant', 'viralverify', 'virfinder', 'virsorter', 'virsorter2', 'breadsticks']

breadsticks: "python ../../tool_envs/unlimited_breadsticks/Cenote_Unlimited_Breadsticks/unlimited_breadsticks.py"
breadsticks_env: "../../tool_envs/unlimited_breadsticks/env"
breadsticks_mem: 5
breadsticks_cpu: 8

deepvirfinder: "python ../../tool_envs/deepvirfinder/DeepVirFinder/dvf.py"
dvf_env: "../../tool_envs/deepvirfinder/env"
deepvirfinder_cores: 1

phamers: "python ../../tool_envs/phamers/PhaMers/scripts/phamer.py"

phigaro: "phigaro"
phigaro_threads: 4

seeker: "predict-metagenome"

vibrant: "python3 ../../tool_envs/vibrant/VIBRANT/VIBRANT_run.py"
vibrant_env: "../../tool_envs/vibrant/env"

viralverify_env: "../../tool_envs/viralverify/env"
viralverify_db: "../../tool_envs/viralverify/nbc_hmms.hmm"
viralverify_threads": 4

virfinder: "../../tool_envs/virfinder/run_virfinder.R"
virfinder_env: "../../tool_envs/virfinder/env"

virsorter: "wrapper_phage_contigs_sorter_iPlant.pl"
virsorter_env: "../../tool_envs/virsorter/env"
virsorter_cpu: 4
virsorter_db: 1
virsorter_data: "../../tool_envs/virsorter/virsorter-data"
virsorter_wrangler: "../post_proc/wrangle_virsorter.sh"

virsorter2: "virsorter run"
virsorter2_env: "../../tool_envs/virsorter2/env"

kingdoms: ["archaea", "bacteria", "fungi", "viral"]

lengths: [500, 1000, 3000, 5000 ]
