# Directories
contigs_dir: "../../data/metagenome_simulation/assembled_reads"
bins_dir: "../../data/metagenome_simulation/binned_contigs"
out_dir: "../../data/classified_simulated"

# House scripts
reformat: "python3 ./reformat.py"
combine: "python3 ./combine.py"
benchmark: "python3 ./benchmark.py"
get_organisms: "../post_proc/get_meta.sh"

# General conda environments
project_env: "../../env"
activate: "/opt/ohpc/pub/apps/anaconda/2020.11/bin/activate"

tools: ['dvf', 'marvel', 'metaphinder', 'seeker', 'vibrant', 'viralverify', 'virfinder', 'virsorter', 'virsorter2']

breadsticks: "python ../../tool_envs/unlimited_breadsticks/Cenote_Unlimited_Breadsticks/unlimited_breadsticks.py"
breadsticks_env: "../../tool_envs/unlimited_breadsticks/env"
breadsticks_mem: 5
breadsticks_cpu: 8

deepvirfinder: "python ../../tool_envs/deepvirfinder/DeepVirFinder/dvf.py"
dvf_env: "../../tool_envs/deepvirfinder/env"
deepvirfinder_cores: 5

marvel_dir: "../../tool_envs/marvel/MARVEL"
marvel: "python3 marvel_bins.py"
marvel_env: "../../tool_envs/marvel/env"
marvel_cores: 4

metaphinder: "../../tool_envs/metaphinder/MetaPhinder/MetaPhinder.py"
metaphinder_env: "../../tool_envs/metaphinder/env"
metaphinder_blast: "../../tool_envs/metaphinder/env/bin"
metaphinder_db: "../../tool_envs/metaphinder/MetaPhinder/database/ALL_140821_hr"

phamers: "python ../../tool_envs/phamers/PhaMers/scripts/phamer.py"

phigaro: "phigaro"
phigaro_threads: 4

seeker: "predict-metagenome"
seeker_env: "../../tool_envs/seeker/env"

vibrant: "python3 ../../tool_envs/vibrant/VIBRANT/VIBRANT_run.py"
vibrant_env: "../../tool_envs/vibrant/env"

viralverify_env: "../../tool_envs/viralverify/env"
viralverify_db: "../../tool_envs/viralverify/nbc_hmms.hmm"
viralverify_threads: 4

virfinder: "../../tool_envs/virfinder/run_virfinder.R"
virfinder_env: "../../tool_envs/virfinder/env"

virsorter: "wrapper_phage_contigs_sorter_iPlant.pl"
virsorter_env: "../../tool_envs/virsorter/env"
virsorter_cpu: 4
virsorter_db: 1
virsorter_data: "../../tool_envs/virsorter/virsorter-data"
virsorter_wrangler: "../post_proc/wrangle_virsorter.sh"

virsorter2: "virsorter run"
virsorter2_env: "../../tool_envs/virsorter2/env"

kingdoms: ["archaea", "bacteria", "fungi", "viral"]

lengths: [500, 1000, 3000, 5000 ]
