# Programs
simulator:
        iss generate
bracken_profiler:
        ./bracken_profiler.py
cat_genomes:
        ./cat_genomes.py
summarize_profile:
        ./summarize_profile.py
megahit:
        megahit
bowtie_build:
        bowtie2-build
bowtie:
        bowtie2
sam_to_bam:
        samtools view -u
sort_bam:
        samtools sort
summarize_depths:
        jgi_summarize_bam_contig_depths
metabat:
        metabat2
make_db:
        makeblastdb
blast:
        blastn
summarize_blast:
        ./summarize_blast.py

# Environments
project_env:
        ../../env
iss_env:
        ../../tool_envs/insilicoseq/env
megahit_env:
        ../../tool_envs/megahit/env
bowtie_env:
        ../../tool_envs/bowtie2/env
samtools_env:
        ../../tool_envs/samtools/env
metabat_env:
        ../../tool_envs/metabat2/env
blast_env:
        ../../tool_envs/blast/env

# Directories
benchmarks_dir:
        ../../data/metagenome_simulation/benchmarks
bracken_dir:
        ../../data/metagenome_simulation/bracken_profiles
profiles_dir:
        ../../data/metagenome_simulation/profiles
refseq_info:
        ../../data/refseq_info/taxonomy.csv
refseq_dir:
        ../../data/refseq
simulated_dir:
        ../../data/metagenome_simulation/simulated_reads
contigs_dir:
        ../../data/metagenome_simulation/assembled_reads
bowtie_index_dir:
        ../../data/metagenome_simulation/bowtie_indices
bowtie_map_dir:
        ../../data/metagenome_simulation/bowtie_mappings
bins_dir:
        ../../data/metagenome_simulation/binned_contigs
blast_dbs_dir:
        ../../data/metagenome_simulation/blast_dbs
blast_out_dir:
        ../../data/metagenome_simulation/blast_out
summary_dir:
        ../../data/metagenome_simulation/summary

# Parameters
## simulate_reads
model:
        ["miseq", "hiseq", "novaseq"]
n_reads:
        --n_reads 20M

## run_blast
e_value: '1e-20'


# Resources
## make_profiles
make_profiles_time: '00:05:00'
make_profiles_ntasks: 1

## summarize_profile
summarize_profile_time: '00:05:00'
summarize_profile_ntasks: 1

## cat_genomes
cat_genomes_time: '00:20:00'
cat_genomes_ntasks: 4

## simulate_reads
simulate_reads_time: '2-00:00:00'
simulate_reads_ntasks: 36

# megahit_assembly
assembly_time: '4:00:00'
assembly_ntasks: 47

# make_bowtie_index
bowtie_indexing_time: '00:30:00'
bowtie_indexing_ntasks: 4

# bowtie_map_reads
bowtie_mapping_time: '04:00:00'
bowtie_mapping_ntasks: 8

# convert_sort_mappings
samtools_time: '00:30:00'
samtools_ntasks: 4

# calculate_depths
calculate_depths_time: '00:15:00'
calculate_depths_ntasks: 4

# metabat_binning
binning_time: '00:10:00'
binning_ntasks: 8

# make_blast_dbs
make_db_time: '00:10:00'
make_db_ntasks: 4

# run_blast
blast_time: '12:00:00'
blast_ntasks: 12

# summarize_blast
summarize_blast_time: '04:00:00'
summarize_blast_ntasks: 6
