simulator:
        iss generate
braken_profiler:
        ./braken_profiler.py
cat_genomes:
        ./cat_genomes.py
simulator_cpus:
        --cpus 8
braken_dir:
        ../../data/braken_profiles
profiles_dir:
        ../../data/profiles
abundances:
        a: "profile_a.txt"
        b: "profile_b.txt"
        c: "profile_c.txt"
simulated_dir:
        ../../data/practice_simulated_reads
model:
        miseq: "miseq"
        hiseq: "hiseq"
        novaseq: "novaseq"
n_reads:
        --n_reads 0.5k
