genome_selector:
        python3 ../genome_selection/genome_selector.py
simulator:
         iss generate
simulator_cpus:
        --cpus 8
genome_dir:
        practice_inputs
selected_dir:
        ../../data/selected_genomes
num_genomes:
        3
class:
        archaea: "archaea"
        bacteria: "bacteria"
        fungi: "fungi"
        viral: "viral"
simulated_dir:
        ../../data/simulated_reads
model:
        miseq
