simulator:
         iss generate
simulator_cpus:
        --cpus 8
genomes:
        practice_inputs/cat_genomes.fasta
abundances:
        profiles/profile_a.txt: "a"
        profiles/profile_b.txt: "b"
        profiles/profile_c.txt: "c"
simulated_dir:
        ../../data/simulated_reads
model:
        miseq: "miseq"
        hiseq: "hiseq"
        novaseq: "novaseq"
n_reads:
        --n_reads 0.5k
