simulator:
         iss generate
simulator_cpus:
        --cpus 8
genomes_dir:
        practice_inputs
abundances:
        a: "profiles/profile_a.txt"
        b: "profiles/profile_b.txt"
        c: "profiles/profile_c.txt"
simulated_dir:
        ../../data/simulated_reads
model:
        miseq: "miseq"
        hiseq: "hiseq"
        novaseq: "novaseq"
n_reads:
        --n_reads 0.5k
