genome_selector:
        python3 ../genome_selection/genome_selector.py
simulator:
         iss generate
simulator_cpus:
        --cpus 8
genome_dir:
        ../genome_selection/tests/inputs/genomes
selected_dir:
        ../../data/selected_genomes
num_genomes:
        3
class:
        non_viral: "non_viral"
        viral: "viral"
simulated_dir:
        ../../data/simulated_reads
model:
        miseq
