simulator:
         iss generate
simulator_cpus:
        --cpus 8
genomes_dir:
        practice_inputs
profiles_dir:
        practice_profiles
abundances:
        a: "profile_a.txt"
        b: "profile_b.txt"
        c: "profile_c.txt"
simulated_dir:
        ../../data/practice_simulated_reads
model:
        miseq: "miseq"
        hiseq: "hiseq"
        novaseq: "novaseq"
n_reads:
        --n_reads 0.5k
