__default__:
        partition: 'windfall'
        group: 'bhurwitz'
        M: 'schackartk@email.arizona.edu'
        time: '{params.time}'
        nodes: '1'
        ntasks: '{threads}'
        mem-per-cpu: '5gb'
        o: 'out/{rule}."{wildcards}".out'
        e: 'err/{rule}."{wildcards}".err'
