__default__:
        partition: 'windfall'
        group: 'bhurwitz'
        M: 'schackartk@email.arizona.edu'
        time: '00:10:00'
        nodes: '1'
        mem-per: '5gb'
        tasks: '94'
        o: 'out/{rule}.{wildcards}.out'
        e: 'err/{rule}.{wildcards}.err'
