# Directories
assembly_dir: "../../data/virome/assemblies"
contig_summary_dir: "../../data/virome/contig_counts"
filtered_contigs_dir: "../../data/virome/filtered_assemblies"
bam_dir: "../../data/virome/bam_files"
bins_dir: "../../data/virome/bins"
bin_summary_dir: "../../data/virome/bin_summaries"
coverage_dir: "../../data/virome/coverages"
out_dir: "../../data/classified_virome"
benchmarks_dir: "../../data/classified_virome/benchmarks"

# House scripts
reformat: "python3 ../classify_simulated/reformat.py"
combine: "python3 ../classify_crc/combine.py"
benchmark: "python3 ../classify_simulated/benchmark.py"
pivot: "python3 ../classify_crc/pivot_wider.py"
filter: "python3 ../classify_crc/filter.py"
summarize_bins: "python3 ../classify_simulated/summarize_bins.py"
contig_lengths: "python3 ../classify_crc/get_lengths.py"
combine_checkv: "python3 ../classify_crc/combine_checkv.py"

# Resources for house scripts
combine_preds_threads: 24
combine_benchmarks_threads: 8
reformat_threads: 8
filter_threads: 8


# Binning
summarize_depths:
        jgi_summarize_bam_contig_depths
binning_ntasks: 24
metabat_env: "../../tool_envs/metabat2/env"
metabat: "metabat2"

# CheckV
checkv_env: "../../tool_envs/checkv/env"
checkv_db: "../../tool_envs/checkv/checkv-db-v1.4"
checkv_cores: 24
checkv_regex: '.*/(?P<sample>\w+_\d+)/checkv/(?P<filename>quality_summary).tsv'

# General conda environments
project_env: "../../env"
activate: "/opt/ohpc/pub/apps/anaconda/2020.11/bin/activate"

tools: ['dvf', 'marvel', 'metaphinder', 'seeker', 'vibrant', 'viralverify', 'virfinder', 'virsorter', 'virsorter2']

deepvirfinder: "python ../../tool_envs/deepvirfinder/DeepVirFinder/dvf.py"
dvf_env: "../../tool_envs/deepvirfinder/env"
deepvirfinder_cores: 24

marvel_dir: "../../tool_envs/marvel/MARVEL"
marvel: "python3 marvel_bins.py"
marvel_env: "../../tool_envs/marvel/env"
marvel_cores: 24

metaphinder: "../../tool_envs/metaphinder/MetaPhinder/MetaPhinder.py"
metaphinder_env: "../../tool_envs/metaphinder/env"
metaphinder_blast: "../../tool_envs/metaphinder/env/bin"
metaphinder_db: "../../tool_envs/metaphinder/MetaPhinder/database/ALL_140821_hr"
metaphinder_threads: 24

seeker: "predict-metagenome"
seeker_env: "../../tool_envs/seeker/env"
seeker_threads: 24

vibrant: "python3 ../../tool_envs/vibrant/VIBRANT/VIBRANT_run.py"
vibrant_env: "../../tool_envs/vibrant/env"
vibrant_threads: 24

viralverify_env: "../../tool_envs/viralverify/env"
viralverify_db: "../../tool_envs/viralverify/nbc_hmms.hmm"
viralverify_threads: 24

virfinder: "../../tool_envs/virfinder/run_virfinder.R"
virfinder_env: "../../tool_envs/virfinder/env"
virfinder_threads: 24

virsorter: "wrapper_phage_contigs_sorter_iPlant.pl"
virsorter_env: "../../tool_envs/virsorter/env"
virsorter_cpu: 24
virsorter_db: 1
virsorter_data: "../../tool_envs/virsorter/virsorter-data"
virsorter_wrangler: "../post_proc/wrangle_virsorter.sh"

virsorter2: "virsorter run"
virsorter2_env: "../../tool_envs/virsorter2/env"
virsorter2_threads: 24
